services:
  sourcebot:
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    # pull_policy: always
    container_name: sourcebot
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/data:/data
    environment:
      - CONFIG_PATH=/data/config.json
      - SOURCEBOT_TELEMETRY_DISABLED=true
