apiVersion: v1
kind: Pod
metadata:
  name: sourcebot
spec:
  containers:
  - name: sourcebot
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 8080
